### ISSUE TITLE
Config does not work/crashes Server

### ISSUE THREAD

**Issue by ProfDrGurkentopf** [cScotPlay/BasicEndOres#1]
If I change the config and try to get on the server afterwards, the server crashes and the game crashes with it. It happens with this mod and also with the BNO mod. 
Version of the Server 1.19 with fabric-0.14.8 .

Is there any solution for this?

**Comment by cScotPlay** [comment]
Been unable to reproduce this.  I'll continue to monitor in future versions.  Thanks for reporting
