### ISSUE TITLE
End Ores are not breakable by player

### ISSUE THREAD

**Issue by Zelioth** [cScotPlay/BasicEndOres#2]
is there a config for this mod anywhere? i can't seem to find one generated. for some reason the Ores from this mod won't let people mine them in the end.
The nether version works fine but we did have this issue before

Minecraft 1.19.2

Forge 43.1.2

BEO - 1.19.2 3.2.0

If you need anymore info let me know

I do not have any mods that change range of block or ore breaking. I don't have any recipe changes or anything

**Comment by cScotPlay** [comment]
Thanks yes updated data generation for the tags to identify mineable blocks didn't properly run.  Updated in newest 3.2.1.
