### ISSUE TITLE
QoL for modpack makers: Default preset datapack available to download

### ISSUE THREAD

**Issue by Geekerandy** [cScotPlay/BasicEndOres#4]
Kinda like the same thing you did with Basic Nether Ores, you had an available datapack ready for people to download and tinker with on Curseforge. Having one for Basic End Ores would also be greatly appreciated.

**Comment by cScotPlay** [comment]
Yes can absolutely do that.  Give just a bit and I should have something posted.

**Comment by allanonmage** [comment]
Where does something like this get posted?

**Comment by cScotPlay** [comment]
Added for 1.20.1 and 1.21.  Check the additional files under the version you are looking for.  I upload the datapack per each version.
