### ISSUE TITLE
Missing "Forge:raw_materials" "Forge:raw_ores" and other tags

### ISSUE THREAD

**Issue by Druark** [cScotPlay/BasicEndOres#7]
The **Raw Ore** items (beo:raw_uranium, beo:raw_zinc, etc) are missing the appropriate tags, examples being the following:
`forge:raw_materials`
`forge:raw_materials/ORE_TYPE`
`forge:raw_ores/ORE_TYPE`

Where `ORE_TYPE` is the name of the ore.

Because these are missing they are unable to be used in many machines from other mods, an example being the **Enrichment Chamber** from *Mekanism*.

Your other mod *Basic Nether Ores* does NOT have this problem as they have the tags assigned, you can test the ores from the two mods side-by-side to see this.

**Comment by cScotPlay** [comment]
Thanks for bringing this up. Currently working all of my mods to update and fix issues

**Comment by cScotPlay** [comment]
This was updated in 1.21.  WIll work on support for 1.20.1.
