### ISSUE TITLE
End gold ore don't drop ore.

### ISSUE THREAD

**Issue by Elderid4** [cScotPlay/BasicEndOres#8]
As title says, end gold ore does not drop the ore. This was tested on a server I am playing on by me and someone else, and also by me in single player. I also tried many different pickaxes. When we mine ores it is supposed to drop the raw gold but does not. I even tried with unenchanted and enchanted tools, and with silk touch. Nothing works. All other gold ore versions work (overworld and nether), and other end ores drops. This is the only one i seem to find that issue with. They told me to get ahold of yall about it on the server network i play on. Thanks!

The version they are using is BasicEndOres-forge-1.20.1-4.1.0
This is in the mod pack Mine Colonies Dimensional Adventure

**Comment by cScotPlay** [comment]
Thanks let me see what I can find out

**Comment by cScotPlay** [comment]
Updated in 1.21 and will add to 1.20.1.
