### ISSUE TITLE
Forge 1.21 loading failure

### ISSUE THREAD

**Issue by Oreoj1234** [cScotPlay/BasicEndOres#9]
I'm just going to type exactly what forge told me when I failed to load:

BasicEndOres (beo) has failed to load correctly
Javanlang.NoSuchFeildError: Class
Net.minecraft.core.registries.Registries does not have member feild 'net.minecraft.resourses.ResourceKey f_279569_'

![Uploading 1719765418841260969404054510184.jpg…]()

**Comment by cScotPlay** [comment]
Thanks for reporting.  This was identified last night and is fixed with version 5.0.2.
